package com.pulperialanegrita;
import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*; import org.json.*; import java.text.*; import java.util.*;

public class MainActivity extends Activity {
 SharedPreferences db; LinearLayout content; ArrayList<Product> products=new ArrayList<>(); ArrayList<Sale> sales=new ArrayList<>(); ArrayList<Cart> cart=new ArrayList<>();
 static class Product {String code,name,brand;double price,cost;int stock;Product(String c,String n,String b,double p,double co,int s){code=c;name=n;brand=b;price=p;cost=co;stock=s;}}
 static class Cart {Product p;int qty;Cart(Product x){p=x;qty=1;}}
 static class Sale {String date;double total;Sale(String d,double t){date=d;total=t;}}
 public void onCreate(Bundle b){super.onCreate(b);db=getSharedPreferences("pulperia",0);load();saleScreen();}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(52);return b;}
 EditText inp(String s){EditText e=new EditText(this);e.setHint(s);e.setSingleLine(true);return e;}
 TextView txt(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(8,10,8,10);return t;}
 String money(double x){return String.format(Locale.getDefault(),"L %.2f",x);}
 void frame(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(8,8,8,8);LinearLayout n=new LinearLayout(this);
  Button a=btn("VENTA"),b=btn("PRODUCTOS"),c=btn("INVENTARIO"),d=btn("HISTORIAL");n.addView(a,new LinearLayout.LayoutParams(0,60,1));n.addView(b,new LinearLayout.LayoutParams(0,60,1));n.addView(c,new LinearLayout.LayoutParams(0,60,1));n.addView(d,new LinearLayout.LayoutParams(0,60,1));r.addView(n);
  ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));a.setOnClickListener(v->saleScreen());b.setOnClickListener(v->productScreen());c.setOnClickListener(v->inventoryScreen());d.setOnClickListener(v->historyScreen());setContentView(r);}
 Product find(String s){for(Product p:products)if(p.code.equals(s))return p;return null;}
 void saleScreen(){frame();content.addView(txt("PULPERÍA LA NEGRITA",24));EditText code=inp("Código de barras / código");content.addView(code);Button add=btn("AGREGAR PRODUCTO");content.addView(add);add.setOnClickListener(v->{Product p=find(code.getText().toString().trim());if(p==null)Toast.makeText(this,"Producto no registrado",0).show();else add(p);code.setText("");renderCart();});content.addView(txt("Escribe el código o usa un lector externo Bluetooth/USB que funcione como teclado.",14));renderCart();}
 void add(Product p){if(p.stock<1){Toast.makeText(this,"Producto agotado",0).show();return;}for(Cart c:cart)if(c.p==p){if(c.qty<p.stock)c.qty++;return;}cart.add(new Cart(p));}
 void renderCart(){content.addView(txt("VENTA ACTUAL",19));if(cart.isEmpty()){content.addView(txt("No hay productos.",16));return;}double total=0;for(Cart c:cart){total+=c.p.price*c.qty;LinearLayout row=new LinearLayout(this);TextView t=txt(c.p.name+"\n"+money(c.p.price)+" x "+c.qty+" = "+money(c.p.price*c.qty),16);Button m=btn("-"),p=btn("+");row.addView(t,new LinearLayout.LayoutParams(0,75,1));row.addView(m,new LinearLayout.LayoutParams(55,60));row.addView(p,new LinearLayout.LayoutParams(55,60));content.addView(row);m.setOnClickListener(v->{c.qty--;if(c.qty<=0)cart.remove(c);saleScreen();});p.setOnClickListener(v->{if(c.qty<c.p.stock)c.qty++;saleScreen();});}content.addView(txt("TOTAL: "+money(total),24));Button save=btn("GUARDAR VENTA");content.addView(save);save.setOnClickListener(v->{for(Cart c:cart)c.p.stock-=c.qty;sales.add(0,new Sale(new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date()),total));save();cart.clear();Toast.makeText(this,"Venta guardada",0).show();saleScreen();});Button clear=btn("VACIAR");content.addView(clear);clear.setOnClickListener(v->{cart.clear();saleScreen();});}
 void productScreen(){frame();content.addView(txt("PRODUCTOS",23));EditText code=inp("Código de barras");content.addView(code);EditText name=inp("Nombre");content.addView(name);EditText brand=inp("Marca");content.addView(brand);EditText price=inp("Precio de venta");price.setInputType(2|8192);content.addView(price);EditText cost=inp("Precio de compra");cost.setInputType(2|8192);content.addView(cost);EditText stock=inp("Existencia");stock.setInputType(2);content.addView(stock);Button save=btn("GUARDAR PRODUCTO");content.addView(save);save.setOnClickListener(v->{try{String c=code.getText().toString().trim(),n=name.getText().toString().trim();if(c.isEmpty()||n.isEmpty()){Toast.makeText(this,"Código y nombre son obligatorios",0).show();return;}double pr=Double.parseDouble(price.getText().toString());double co=cost.getText().toString().isEmpty()?0:Double.parseDouble(cost.getText().toString());int st=stock.getText().toString().isEmpty()?0:Integer.parseInt(stock.getText().toString());Product old=find(c);if(old==null)products.add(new Product(c,n,brand.getText().toString(),pr,co,st));else{old.name=n;old.brand=brand.getText().toString();old.price=pr;old.cost=co;old.stock=st;}save();Toast.makeText(this,"Producto guardado",0).show();productScreen();}catch(Exception e){Toast.makeText(this,"Revisa los datos",0).show();}});content.addView(txt("CATÁLOGO",19));for(Product p:products)content.addView(txt(p.name+" | "+p.brand+"\nCódigo: "+p.code+" | Precio: "+money(p.price)+" | Stock: "+p.stock,15));}
 void inventoryScreen(){frame();content.addView(txt("INVENTARIO",23));if(products.isEmpty()){content.addView(txt("No hay productos.",16));return;}for(Product p:products){TextView t=txt(p.name+"\nStock: "+p.stock+"   Precio: "+money(p.price),17);if(p.stock<=3)t.setTextColor(Color.RED);content.addView(t);}}
 void historyScreen(){frame();content.addView(txt("HISTORIAL DE VENTAS",23));double total=0;for(Sale s:sales)total+=s.total;content.addView(txt("Ventas: "+sales.size()+"\nTotal: "+money(total),18));for(Sale s:sales)content.addView(txt(s.date+"   "+money(s.total),16));}
 void save(){try{JSONArray a=new JSONArray();for(Product p:products){JSONObject o=new JSONObject();o.put("code",p.code);o.put("name",p.name);o.put("brand",p.brand);o.put("price",p.price);o.put("cost",p.cost);o.put("stock",p.stock);a.put(o);}JSONArray b=new JSONArray();for(Sale s:sales){JSONObject o=new JSONObject();o.put("date",s.date);o.put("total",s.total);b.put(o);}db.edit().putString("products",a.toString()).putString("sales",b.toString()).apply();}catch(Exception ignored){}}
 void load(){try{JSONArray a=new JSONArray(db.getString("products","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);products.add(new Product(o.optString("code"),o.optString("name"),o.optString("brand"),o.optDouble("price"),o.optDouble("cost"),o.optInt("stock")));}JSONArray b=new JSONArray(db.getString("sales","[]"));for(int i=0;i<b.length();i++){JSONObject o=b.getJSONObject(i);sales.add(new Sale(o.optString("date"),o.optDouble("total")));}}catch(Exception ignored){}}
}
