name: Compile APK Modern
on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Unzip and force deep structural search
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        mkdir -p extracted_data
        unzip -o *.zip -d extracted_data || true
        
        # Buscar en que subcarpeta real esta el archivo settings.gradle.kts o settings.gradle
        REAL_PATH=$(find extracted_data -name "settings.gradle.kts" -o -name "settings.gradle" -exec dirname {} \; | head -n 1)
        echo "The project source files are located at: $REAL_PATH"
        
        # Mover todo el contenido encontrado a la raiz limpia del servidor
        cp -r $REAL_PATH/* . 2>/dev/null || true
        cp -r $REAL_PATH/.[!.]* . 2>/dev/null || true
        rm -rf extracted_data

    - name: Setup Java 17 (Required)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle 8.9 (Required)
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.9'

    - name: Build Android APK
      run: |
        gradle clean assembleDebug --no-daemon

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: PulperiaLaNegrita-debug
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          **/build/outputs/apk/debug/*.apk
